name 'exim4'
maintainer 'Andrew Ying'
maintainer_email 'andrew.ying@jano.rocks'
license 'GPL-3.0'
description 'Installs/Configures Exim4'
long_description 'Chef cookbook for building and installing Exim, version 4'
version '0.1.0'
chef_version '>= 14.0'
supports 'ubuntu'
supports 'debian'

issues_url 'https://github.com/JanoCodes/ChefExim4/issues'
source_url 'https://github.com/JanoCodes/ChefExim4'
