name 'exim4'
maintainer 'Andrew Ying'
maintainer_email 'andrew.ying@jano.rocks'
license 'GPL-3.0'
description 'Installs/Configures exim4'
long_description 'Installs/Configures exim4'
version '0.1.0'
chef_version '>= 14.0'

issues_url 'https://github.com/JanoCodes/ChefExim4/issues'
source_url 'https://github.com/JanoCodes/ChefExim4'
